const productList = [
  {
    id: 0,
    category: 'dresses',
    name: 'Green Summer Dress',
    price: 110,
    sizes: ['S', 'M', 'L'],
    image_id: 'ecommerce-store/zq4lzfasfde5g8cjh0m6.jpg',
  },
  {
    id: 1,
    category: 'dresses',
    name: 'Navy Polka Dot Summer Dress',
    price: 70,
    sizes: ['S', 'M', 'L'],
    image_id: 'ecommerce-store/xene5airuesxubuas3zm.jpg',
  },
  {
    id: 2,
    category: 'dresses',
    name: 'White Polka Dot Summer Dress',
    price: 70,
    sizes: ['S', 'M', 'L'],
    image_id: 'ecommerce-store/px3x4t2wnkqyty35hlsm.jpg',
  },
  {
    id: 3,
    category: 'dresses',
    name: 'Red Cocktail Dress',
    price: 150,
    sizes: ['S', 'M', 'L'],
    image_id: 'ecommerce-store/uvuje9ubfntaaxoq5opt.jpg',
  },
  {
    id: 4,
    category: 'dresses',
    name: 'Short Boho Dress',
    price: 80,
    sizes: ['S', 'M', 'L'],
    image_id: 'ecommerce-store/vzacmrfgfgswijptsqyl.jpg',
  },
  {
    id: 5,
    category: 't-shirts',
    name: 'Red T-Shirt',
    price: 30,
    sizes: ['S', 'M', 'L'],
    image_id: 'ecommerce-store/iuz5ppuruiq5kph22m3j.jpg',
  },
  {
    id: 6,
    category: 't-shirts',
    name: 'Purple T-Shirt',
    price: 30,
    sizes: ['S', 'M', 'L'],
    image_id: 'ecommerce-store/egtxjr7yrkdi4fikei9m.jpg',
  },
  {
    id: 7,
    category: 't-shirts',
    name: 'Green T-Shirt',
    price: 30,
    sizes: ['S', 'M', 'L'],
    image_id: 'ecommerce-store/awisvalpjyiwlicggpse.jpg',
  },
  {
    id: 8,
    category: 't-shirts',
    name: 'Blue Gray T-Shirt',
    price: 30,
    sizes: ['S', 'M', 'L'],
    image_id: 'ecommerce-store/mn0ucnz6hedhttnjiaqk.jpg',
  },
  {
    id: 9,
    category: 'sunglasses',
    name: 'Clear Frame Rose-Tinted Sunglasses',
    price: 55,
    sizes: ['One Size'],
    image_id: 'ecommerce-store/xkx2dfzkyl2rl5o78ugc.jpg',
  },
  {
    id: 10,
    category: 'sunglasses',
    name: 'Pink Frame Sunglasses',
    price: 60,
    sizes: ['One Size'],
    image_id: 'ecommerce-store/n7ydt8zx2xxzbnaqhtex.jpg',
  },
  {
    id: 11,
    category: 'sunglasses',
    name: 'Black Metal Frame Sunglasses',
    price: 70,
    sizes: ['One Size'],
    image_id: 'ecommerce-store/evoc67tjkgiggxydttcm.jpg',
  },
  {
    id: 12,
    category: 'sunglasses',
    name: 'Black Frame Sunglasses',
    price: 60,
    sizes: ['One Size'],
    image_id: 'ecommerce-store/xrym1cmz1yvphkz9ihug.jpg',
  },
  {
    id: 13,
    category: 'sunglasses',
    name: 'Standout Off-White Frame Sunglasses',
    price: 80,
    sizes: ['One Size'],
    image_id: 'ecommerce-store/z5gu1kb01virprrjhnk7.jpg',
  },
];

export default productList;
